---
title: "Lab_7"
author: "Laura Gattis, Emmanuel Maduneme, Megan Denneny, Sam Lorenzo"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      eval = TRUE,
                      message = FALSE,
                      fig.width = 6.5, 
                      fig.height = 8)
library(datapasta)
library(dplyr)
library(tidyverse)
library(psych)
library(skimr)
library(readr)
library(janitor)
library(rio)
library(here)
library(palmerpenguins)
library(ggthemes)
library(fivethirtyeight)
library(ggridges)
library(DT)
library(tinytex)
```


### Commit 1: Loading Data 
```{r}
here()
star_df <- import(here("Data", "star.csv"), setclass = "tbl_df") %>% 
  clean_names() %>% 
  characterize()
names(star_df)
```

### Commit2
Hashtag can be a form of activism [@ofori2018hashtag]. On another issue, according to @peters2022communicating it is essential to communicate climate change in a way that protects our health. 

### Commit 3
```{r commit 3}

star_df %>% 
  select(sex, frl, tmathss, treadss) %>% 
 
  group_by(sex, frl) %>% 
  summarize(math_mean = round(mean(tmathss), digits = 2),
           math_sd = round(sd(tmathss),digits = 2),
           rdg_mean = round(mean(treadss), digits = 2),
           rdg_sd = round(sd(treadss), digits = 2)
  ) %>% 
  gt()

  
```



### Commit 4
```{r Commit 4}
star_df %>% 
  ggplot(aes(x = totexp, y = tmathss)) +
  geom_point(col = "Grey") +
  geom_smooth(aes(col = frl), method = lm) +
  labs(x = "Teacher Experience(years)",
         y = "Total Maths Score",
         title = "Relation between teacher experience and maths scores",
         subtitle = "Seperate regression lines displayed by free/reduced lunch status") +
  scale_color_discrete(name = "Lunch Status", labels = c("Free/Reduced Price Meals", "Paid Meals"))+
   theme(legend.position="bottom") 

```



\newpage
# References\centering